version: "3.9"    
services:
  nginx:
    image: lightruncom/lightrun-broker-rhel:01 #Set your image here builded from docker folder
    environment:
      LIGHTRUN_SERVER:  #Set endpoint of your lightrun server
    volumes:
      - type: bind
        source: ./conf/certs/
        target: /etc/nginx/conf.d/certs/
      - type: bind
        source: ./conf/nginx.conf.template
        target: /etc/nginx/nginx.conf.template
    ports:
      - "443:443"
    restart: always
    dns:
      - 8.8.8.8 # Set here your public DNS for resolving original Lightrun endpoint
    

  