version: "3.3"
services:
  nginx:
    image: lightruncom/lightrun-broker:latest.layer4
    ports:
    - "443:443"
    environment:
      LIGHTRUN_SERVER: <tenant>.client.lightrun.com
    volumes:
      - type: bind
        source: ./conf/default.template
        target: /tmp/default.template
    restart: always
    dns:
      - 8.8.8.8 # Set here your public DNS for resolving original Lightrun endpoint
