version: "3.9"    
services:
  nginx:
    build: docker/.
    volumes:
      - type: bind
        source: ./conf/certs/
        target: /etc/nginx/conf.d/certs/
      - type: bind
        source: ./conf/nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - "443:443"
    restart: always
    dns:
      - 8.8.8.8 # Set here your public DNS for resolving original Lightrun endpoint
    

  