version: "3.9"    
services:
  nginx:
    image: nginx:1.23.1
    environment:
      LIGHTRUN_SERVER: https://app.lightrun.com # Set endpoint of your lightrun server
    volumes:
      - type: bind
        source: ./conf/certs/
        target: /etc/nginx/conf.d/certs/
      - type: bind
        source: ./conf/templates/
        target: /etc/nginx/templates/
    ports:
      - "443:443"
    restart: always
    dns:
      - 8.8.8.8 # Set here your public DNS for resolving original Lightrun endpoint

  